### ISSUE TITLE
"Invalid params: Invalid block number: missing 0x prefix."

### ISSUE THREAD

**Issue by nikunjsmartsense** [PaulRBerg/confidential-tokens#2]
Hello there! i am trying to make transactions on kovan testnet. each time i am getting error 
Node error: {"code":-32602,"message":"Invalid params: Invalid block number: missing 0x prefix."}
not able to understand why getting this error i have tried by sending each parameter in hex format still not working

**Comment by PaulRBerg** [comment]
Hey @nikunjsmartsense, the tutorial and the repo only work with Rinkeby. Sorry for not being descriptive enough!
